name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DIRECTUS_EMAIL: admin@local.com
      DIRECTUS_PASSWORD: adminpassword
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Setup buildx
      uses: docker/setup-buildx-action@v3
    - name: Setup node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Unit Tests
      run: yarn test:coverage
    - name: Setup Test Infrastructure
      run: |
        docker compose up -d postgres directus
    - name: E2E Tests
      run: |
        yarn playwright install --with-deps
        yarn test:e2e
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
    - name: Build images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        sbom: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Auth ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    - name: Push images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        sbom: true
        push: true
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    - name: Create Release Pull Request
      uses: changesets/action@v1
      with:
        version: changeset version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
