name: Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Setup node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: Git Config
      run: |
        git config user.name ${{ github.actor }}
        git config user.email "${{ github.actor }}@users.noreply.github.com"
    - name: Bump Version
      run: |
        yarn
        yarn beachball bump
        echo "NEXT_VERSION=$(node -e 'console.log(require(\"./package.json\").version)')" >> $GITHUB_ENV
    - name: Create Branch
      run: |
        NEW_BRANCH="release_$NEXT_VERSION"
        git switch -c $NEW_BRANCH
        git add .
        git commit -m "$NEXT_VERSION"
        git push --no-verify --verbose origin $NEW_BRANCH
        echo "NEW_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV
    - name: Create Pull Request
      run: |
        gh pr create -B main -H $NEW_BRANCH --title 'Version $NEXT_VERSION'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}